spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:replyboard
    driver-class-name: org.h2.Driver
    username: sa
    password: